### PR TITLE
Support for Trip Requests

### PR DESCRIPTION
**Pull request by arunthampi**

### CODE REVIEW

**Comment by arunthampi** [comment]
Sorry this is a big pull request but it has the following:
- [ ] Re-organization of code
- [ ] Add specs
- [ ] Add support for making trip requests
- [ ] Add support for sandbox API

**Comment by arunthampi** [comment]
Also will leave it upto you to change version numbers.

**Comment by arunthampi** [comment]
Sweet, let me know when you've cut a release on rubygems! :raised_hands:

**Comment by sishen** [comment]
@arunthampi Just uploaded to rubygems. Thank you very much!

**Comment by arunthampi** [comment]
thanks!

**Pull request merged**
